# Generated by Django 3.2 on 2021-04-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_date_joined_tweet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
